Xcentium.Test/Models/ErrorViewModel.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace Xcentium.Test.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Xcentium.Test/Models/Scrape.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Xcentium.Test.Web.Models
{

    public class WebImage
    {
        public string ImageUrl { get; set; }
        public string ImageContext { get; set; }
        public int Width { get; set; }
        public int Length { get; set; }
        public int Size { get; set; }
    }

    public class WebWord
    {
        public string Word { get; set; }
        public int Count { get; set; }
    }

    public class Scrape
    {
        public string PageUrl { get; set; }
        public string Comment { get; set; }
        public List<WebImage> ImageList { get; set; }
        public List<WebWord> WordCount { get; set; }

    }
}

Xcentium.Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Xcentium.Test.Web.Models;

namespace Xcentium.Test.Web.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index(string errorMessage)
        {
            if (errorMessage != String.Empty)
            {
                ViewData["Message"] = errorMessage;
            }
            return View();
        }

        public IActionResult About()
        {

            return View();
        }

        public IActionResult Contact()
        {

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Xcentium.Test/Controllers/ScrapeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Xcentium.Test.Web.Models;
using HtmlAgilityPack;
using Microsoft.AspNetCore.WebUtilities;


namespace Xcentium.Test.Web.Controllers
{
    public class ScrapeController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string PageUrl)
        {

            Scrape pageData = ScrapePageData(PageUrl);
            if (String.IsNullOrWhiteSpace(PageUrl) || String.IsNullOrEmpty(pageData.PageUrl))
            {
                return RedirectToAction("Index", "Home", "Invalid");
            }
            return View(pageData);
        }

        public Scrape ScrapePageData(string url)
        {
            Scrape scrape = new Scrape();

            try
            {
                    if (!url.StartsWith("http"))
                    {
                        url = "http://" + url;
                    }
                    HtmlDocument doc = new HtmlWeb().Load(url);
                    scrape.PageUrl = url;

                    //Get Images
                    scrape.ImageList = GetImages(doc, new Uri(url));

                    //Get Words
                    scrape.WordCount = GetWords(doc);
            }
            catch (Exception e)
            {
                //Allow to go to view.
                scrape.PageUrl = string.Empty;
                scrape.Comment = e.Message;
            }

            return scrape;
        }

        public List<WebImage> GetImages(HtmlDocument doc, Uri baseurl)
        {
            List<WebImage> _images = new List<WebImage>();

            IEnumerable<String> urls = doc.DocumentNode.Descendants("img")
                                       .Select(e => e.GetAttributeValue("src", null))
                                       .Where(s => !String.IsNullOrEmpty(s));

            foreach (String url in urls)
            {
                var _url = new Uri(baseurl, url);
                _images.Add(new WebImage { ImageContext = "img", ImageUrl = _url.AbsoluteUri });
            }

            return _images;
        }

        public List<WebWord> GetWords(HtmlDocument doc)
        {
            List<WebWord> _words = new List<WebWord>();
            string wordstring = string.Empty;
            IEnumerable<HtmlNode> nodes = doc.DocumentNode.Descendants()
                                             .Where(n => n.NodeType == HtmlNodeType.Text
                                                      && n.ParentNode.Name != "script"
                                                      && n.ParentNode.Name != "style");

            foreach (HtmlNode node in nodes)
            {
                string _w = System.Net.WebUtility.HtmlDecode(node.InnerText).Replace("-","").Trim();

                if (!string.IsNullOrWhiteSpace(_w))
                {
                    wordstring += _w;
                }

            }

            var ws = wordstring.Split(new[] { " " }, StringSplitOptions.RemoveEmptyEntries)
                                        .GroupBy(r => r)
                                        .Select(grp => new WebWord
                                        {
                                            Word = grp.Key,
                                            Count = grp.Count()
                                        })
                                        .OrderByDescending(x => x.Count);

            foreach (WebWord w in ws)
            {
                _words.Add(new WebWord { Word = w.Word, Count = w.Count });
            }

            return _words;
        }

    }
}

Xcentium.Test/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<section id="spacer"></section>
<section id="about">
    <div class="container">
        <h1>About this Project</h1>
        <h2>Web Page Parser</h2>

        <h3>Purpose:</h3>
        <p>Write a small user friendly program that allows the user to type a URL for a given website page and the program will then do the following:</p>
        <ul>
            <li>List all images and show them to the user appropriately in a carousel or gallery control of some kind (borrow from the internet or write your own)</li>
            <li> Count all the words (display the total) and display the top 10 occurring words and their count (eithers as a table or chart of some kind, again you choose or write your own)</li>
        </ul>

        <h3>Documentation</h3>
        <p>We will have a 2 page website that will include:</p>
        <ul>
            <li>
                Landing Page
            </li>
            <li>
                Results Page
                <ul>
                    <li>Summary</li>
                    <li>Image List</li>
                    <li>Top 10 Words</li>
                </ul>
            </li>
            <li>
                About Page
            </li>
            <li>
                Contact Page
            </li>
        </ul>
        
        <a href="~/img/Xcentium Test Project.pdf" target="_new">Download the Project Documentation</a>

        <h3>Source Code</h3>
        <p>The source code can be found at the author's BitBucket account.</p>  <a href="https://bitbucket.org/markfulton3/xcentium-test" target="_new">Xcentium Test Project</a>
    </div>
</section>

Xcentium.Test/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<section id="spacer"></section>
<section id="contact">
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <h3>@ViewData["Message"]</h3>

        <address>
            Mark Fulton<br />
            1323 South 211th St<br/>
            Omaha, NE<br />
            <abbr title="Phone">P:</abbr>
            402.301.7308
        </address>

        <address>
            <strong>Email:</strong> markfulton3@gmail.com
        </address>
        <div class="col-md-12">
            <ul class="list-inline social-buttons">
                <li class="list-inline-item">
                    <a href="https://twitter.com/markfulton12" target="_new">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.facebook.com/markfulton3" target="_new">
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.linkedin.com/in/mark-fulton-a5b3986/" target="_new">
                        <i class="fa fa-linkedin"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>

Xcentium.Test/Views/Home/Index.cshtml
@model Scrape
@{
    ViewData["Title"] = "Home Page";
}
<section id="spacer"></section>
<section id="masthead">
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">an Xcentium Test Project</div>
            <div class="intro-heading text-uppercase">Let's Scrape a Web Page</div>
            <div class="row">
                <div class="col-lg-12">
                    @ViewData["Message"];

                    <form asp-controller="Scrape" asp-action="Index" id="scrapeForm" method="post">
                        @Html.AntiForgeryToken()
                        <div class="row">
                            <div class="col-md-10">
                                <div class="form-group">
                                    <input asp-for="PageUrl" class="form-control" placeholder="http://someweb.com/page" />
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="pull-right">
                                    <button id="btnGetPageData" class="btn btn-primary btn-xl text-uppercase" type="submit">Start</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Xcentium.Test/Views/Scrape/Index.cshtml
@using Xcentium.Test.Web.Models
@model Xcentium.Test.Web.Models.Scrape
@{
    ViewData["Title"] = "Scrape Data";
}
<section id="spacer"></section>
<section id="scrape">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Enter Web Page</h2>
                <h3 class="section-subheading text-muted">Gather text and image data on this web page.</h3>
            </div>
        </div>
        <div class="row">
            @Html.ValidationMessage("Error")

            <div class="col-lg-12">
                <form asp-controller="Scrape" asp-action="Index" id="scrapeForm" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <input asp-for="PageUrl" class="form-control" placeholder="http://someweb.com/page" />
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="pull-right">
                                <button id="btnGetPageData" class="btn btn-primary btn-xl text-uppercase" type="submit">Start</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<section id="results">
    <div class="col-lg-12">
        <div class="alert-info"></div>
    </div>

    @{

        if (ViewData.ModelState.IsValid)
        {
            if (Model.WordCount.Count == 0)
            {
            <div class="text-danger text-center">The web page did not return any results. Please check your input.</div>

            }
            else
            {
            <div class="Summary">
                <h1>Summary</h1>
                <strong>Page Url</strong>: @Model.PageUrl<br />
                <strong>Image Count</strong>: @Model.ImageList.Count<br />
                <strong>Word Count</strong>: @Model.WordCount.Count
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div id="images">
                        <h1>Image List</h1>
                        <div class="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 300 }'>
                            @{
                                if (Model.ImageList.Count != 0)
                                {
                                    foreach (WebImage image in Model.ImageList)
                                    {
                                        <div class="grid-item"><img src="@image.ImageUrl" /></div>
                                    }
                                }
                                else
                                {
                                    <div class="text-danger text-center">The web page did not return any images.</div>

                                }
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div id="words">
                        <h1>Top 10 Recurring Words</h1>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Word</th>
                                    <th>Count</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    if (Model.WordCount.Count != 0)
                                    {
                                        var maxCount = 10;
                                        if (Model.WordCount.Count < 10)
                                        {
                                            maxCount = Model.WordCount.Count;
                                        }


                                        for (int i = 0; i < maxCount; i++)
                                        {
                                            <tr>
                                                <td>@Model.WordCount[i].Word</td>
                                                <td>@Model.WordCount[i].Count</td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="2">The web page did not return any text.</td>
                                        </tr>

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            }
        }
    }
</section>
<section id="popup">
    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Preview</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="imagepreview" style="width: 400px; height: 264px;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</section>

Xcentium.Test/Views/Shared/_Footer.cshtml
<!--Footer-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright © Mark Fulton 2017</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/markfulton12" target="_new">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/markfulton3" target="_new">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/mark-fulton-a5b3986/" target="_new">
                            <i class="fa fa-linkedin"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li class="list-inline-item">
                        <a href="/Home/About">About</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="/Home/Contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Xcentium.Test/Views/Shared/_Header.cshtml
<!--Header-->
<header class="header-main container-fluid no-padding">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Scrapium</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Scrape</a></li>
                    <li><a href="/Home/Contact">Contact</a></li>
                    <li><a href="/Home/About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Xcentium.Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Mark Fulton</title>

    <!--Fonts-->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    

    <environment include="Development">
        <link rel="stylesheet" href="~/css/main.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/main.css" />
    </environment>
    
</head>
<body>
    
    @{ Html.RenderPartial("_Header"); }
    <!--Body-->
    <div class="body-content">
        @RenderBody()
    </div>
   @{ Html.RenderPartial("_Footer"); }

    

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js" asp-append-version="true"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js" asp-append-version="true"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
   
</body>
</html>